apiVersion: v1
kind: Service
metadata:  
  name: application-service
spec:
  selector:    
    app: sfapp
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
