apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-09-20T10:19:46Z
  labels:
    run: sfapp
  name: sfapp-lb
  namespace: default
  resourceVersion: "90324"
  selfLink: /api/v1/namespaces/default/services/sfapp-lb
  uid: b32185b7-bcbe-11e8-a39b-42010a800033
spec:
  clusterIP: 10.35.251.19
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32374
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: sfapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
