apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: sfapp
  name: sfapp
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/sfapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sfapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: sfapp
    spec:
      containers:
      - env:
        - name: CASSANDRA_HOST
          value: 10.32.0.16
        image: gcr.io/sfdatascience-216716/sfapp:v2.16
        imagePullPolicy: IfNotPresent
        name: sfapp
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
