---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-volume1
  labels:
    type: local
    app: cassandra
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-volume1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-volume2
  labels:
    type: local
    app: cassandra
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/cassandra-volume2
  persistentVolumeReclaimPolicy: Recycle
